project:
  type: website

website:
  title: "Ruoqing Zhu' Personal Website"
  favicon: files/favicon.ico
  navbar:
    collapse: false          # <- prevents the icon/hamburger menu
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: members.qmd
        text: Members
      - href: publications.qmd
        text: Publications
      - href: software.qmd
        text: Software
      - href: teaching.qmd
        text: Teaching
    right:
      - href: https://scholar.google.com/citations?user=YOUR_ID
        text: "<i class='ai ai-google-scholar ai-lg' aria-hidden='true'></i>"  
      - icon: github
        href: https://github.com/teazrq
    classes: "justify-content-center"
format:
  html:
    page-layout: full
    theme:
      light: flatly
      dark: darkly
    toc: false
    link-external-newwindow: true
    css:
      - academicons/css/academicons.min.css
      - css/styles.css
      - css/page-style.css
    include-after-body: files/footer.html
